# Generated by Django 6.0.3 on 2026-03-30 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='car_name',
            new_name='name',
        ),
    ]
